### ISSUE TITLE
首页文字修改

### ISSUE THREAD

**Issue by 1022ranji** [darwinia-network/home#176]
- [x] Smart App 改为 Smart Module
![image](https://user-images.githubusercontent.com/80877629/132628416-3a96834c-c4e3-4618-83e0-62abc42016e4.png)
![image](https://user-images.githubusercontent.com/80877629/132630021-d53163d7-4dc4-4094-9041-1dedb5273b72.png)
- [x] 切换成中文模式的时候下图中文字没有切换成中文
![image](https://user-images.githubusercontent.com/80877629/132630529-7acd09c0-5e13-4506-ae85-2f42dbe9e839.png)
![image](https://user-images.githubusercontent.com/80877629/132630557-43b47f69-8edf-4d70-8a49-092e013e3b93.png)
- [x] “虫洞”在中文模式下可以不翻译
![image](https://user-images.githubusercontent.com/80877629/132630864-c60b552e-f045-45b3-a8be-24f6c0702765.png)

**Comment by JayJay1024** [comment]
> * [ ]  Smart App 改为 Smart Module
>   ![image](https://user-images.githubusercontent.com/80877629/132628416-3a96834c-c4e3-4618-83e0-62abc42016e4.png)
>   ![image](https://user-images.githubusercontent.com/80877629/132630021-d53163d7-4dc4-4094-9041-1dedb5273b72.png)
> * [ ]  切换成中文模式的时候下图中文字没有切换成中文
>   ![image](https://user-images.githubusercontent.com/80877629/132630529-7acd09c0-5e13-4506-ae85-2f42dbe9e839.png)
>   ![image](https://user-images.githubusercontent.com/80877629/132630557-43b47f69-8edf-4d70-8a49-092e013e3b93.png)
> * [ ]  “虫洞”在中文模式下可以不翻译
>   ![image](https://user-images.githubusercontent.com/80877629/132630864-c60b552e-f045-45b3-a8be-24f6c0702765.png)

早上想说这个忘了，这些翻译在notion有文档吗？好像没找到中文翻译

**Comment by 1022ranji** [comment]
这个链接 https://www.notion.so/itering/PRD-f34835f3a56b45c4b9c56c7454642835
可能表现的不是很明显，在括号里面的是相应的中文。
![image](https://user-images.githubusercontent.com/80877629/132631732-5785b077-ab7a-412f-b0c4-c9f0fd469412.png)
