### ISSUE TITLE
wrong partner link and logo for glitch.finance

### ISSUE THREAD

**Issue by raidoh** [darwinia-network/home#195]
wrong partner link and logo for glitch.finance

![2021-11-02 08 48 53](https://user-images.githubusercontent.com/4649680/139806314-ffeb4da7-f773-4859-a308-b685bdd443df.jpg)

Regards

Set

**Comment by 1022ranji** [comment]
Could you please take a screenshot? I can’t reproduce it.
When I click this icon, it will show like this:
![image](https://user-images.githubusercontent.com/80877629/139806911-5869ac21-7f98-4da5-b85c-302be0f03727.png)

**Comment by raidoh** [comment]
it links to glitch.com but the right site is https://glitch.finance/

**Comment by 1022ranji** [comment]
OK, I get it.

**Comment by 1022ranji** [comment]
cc @JayJay1024 替换 website 中 ecosystem projects 栏目中的 glitch 链接以及图片
![image](https://user-images.githubusercontent.com/80877629/139808139-7da87302-0f94-4ef0-bcec-8dc5a19e1830.png)

正确链接：https://glitch.finance/
正确Logo:
![Glitch-logo-110128](https://user-images.githubusercontent.com/80877629/139807989-4f716853-b41c-44e1-b26b-
d5948a524fcf.png)

**Comment by raidoh** [comment]
Thanks for the quick response!

Set

**Comment by JayJay1024** [comment]
> cc @JayJay1024 替换 website 中 ecosystem projects 栏目中的 glitch 链接以及图片 ![image](https://user-images.githubusercontent.com/80877629/139808139-7da87302-0f94-4ef0-bcec-8dc5a19e1830.png)
> 
> 正确链接：https://glitch.finance/ 正确Logo: ![Glitch-logo-110128](https://user-images.githubusercontent.com/80877629/139808335-f77297fc-76b5-4c3b-9651-a5694baff9bf.png)

fixed: 9b40e0d

**Comment by raidoh** [comment]
great - thanks!
