### ISSUE TITLE
PLO页面：插件中有特殊账户格式时，连接钱包时报错

### ISSUE THREAD

**Issue by 1022ranji** [darwinia-network/home#203]
插件里面有一个特殊的账户格式，设为不可见之后就可以连接打开了。当使用polkadot.js.org没有问题。
![image](https://user-images.githubusercontent.com/80877629/141729943-3640cd69-cace-4dc7-ad28-964f9d7f418e.png)
![image](https://user-images.githubusercontent.com/80877629/141730085-8c25604c-3142-4bd8-a403-134023bd358b.png)

**Comment by 1022ranji** [comment]
issue 重复

**Comment by HackFisher** [comment]
Related #204
