### ISSUE TITLE
PLO页面｜这里的圆圈需要变成实心的，“To be determined” 改为 “NOV 15 2021”

### ISSUE THREAD

**Issue by 1022ranji** [darwinia-network/home#218]
https://darwinia.network/plo
To be determined 改为 “NOV 15 2021”
![image](https://user-images.githubusercontent.com/80877629/142820761-f757b71a-8ed1-4f79-917f-7309f8c8ebfc.png)

**Comment by chunqiuyiyu** [comment]
fixed in https://github.com/darwinia-network/home/pull/219

**Comment by 1022ranji** [comment]
done
