### ISSUE TITLE
Bottom bar needs some docs changes

### ISSUE THREAD

**Issue by ZolaxZola** [darwinia-network/home#316]
© 2022 Darwinia Network
It should be © not @ , which represents Copyright
https://darwinia.network/
![image](https://user-images.githubusercontent.com/102211220/185304512-9d8b737f-4102-4b93-a326-4d926b7ab1fc.png)

**Comment by isunaslabs** [comment]
The design image had an @ on it and not a ©, but I'll update it to a © accordingly. Thank you for noticing that 😀
