### ISSUE TITLE
Add more introduction about EVM and smart contract

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/home#331]
I think the current introduction of EVM and smart contracts on our official website is a bit weak, or very little. This is not right, we need to adjust it and add an introduction to the EVM chain and smart contracts, especially after Darwinia2 is launched. Doing the cross-chain dApp market does not hinder the dApp market.

**Comment by isunaslabs** [comment]
@wuminzhe @1022ranji We'll have to make some updates.
