### ISSUE TITLE
please adjust these links after crab 2.0 staking and account migration dapps release

### ISSUE THREAD

**Issue by 1022ranji** [darwinia-network/home#332]
Current Version：
<img width="874" alt="image" src="https://user-images.githubusercontent.com/80877629/223899913-0809a294-e118-4512-8521-3b33a8f8c0a5.png">

New:
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/80877629/223899871-9f974b8c-6066-4ba7-ae5d-8227ed09d477.png">
links please refer to: https://www.notion.so/itering/Darwinia-2-0-Website-adjustment-3af9c034c17346189e4f7acdca582ce6

**Comment by isunaslabs** [comment]
ok
