### ISSUE TITLE
链接失效

### ISSUE THREAD

**Issue by 1022ranji** [darwinia-network/home#336]
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/80877629/231340266-27080f35-39c9-4677-a3c0-27d108b8153a.png">
https://darwinia.network/#/developers 这个页面中有些文档链接失效了， @wuminzhe 麻烦帮忙确认下最新的文档链接，然后 @isunaslabs 帮忙更新一下

**Comment by wuminzhe** [comment]
我建议这里先全部hidden吧，感觉文档需要准备得更充分些

**Comment by isunaslabs** [comment]
@1022ranji do you approve this method?

**Comment by wuminzhe** [comment]
yes, hide them all. put a 'under construction' statement. @1022ranji

**Comment by 1022ranji** [comment]
like this one?
<img width="241" alt="image" src="https://user-images.githubusercontent.com/80877629/231356809-c0aa2bc7-8f6d-48f8-bb10-77bd44439d52.png">

**Comment by isunaslabs** [comment]
I think this option is fine. Let's see what Aki thinks of it.

**Comment by wuminzhe** [comment]
> like this one? <img alt="image" width="241" src="https://user-images.githubusercontent.com/80877629/231356809-c0aa2bc7-8f6d-48f8-bb10-77bd44439d52.png">
something like this "Introduction".
<img width="1398" alt="image" src="https://user-images.githubusercontent.com/1608576/231358381-d523c563-a907-48f2-af9e-6f541874aecb.png">

**Comment by 1022ranji** [comment]
这几个也这么显示？感觉不太行，整个页面能用的有效信息太少了。
放个文档名字备注 updating, 即使没有放在那里别人也会知道这里将会有什么。
<img width="1195" alt="image" src="https://user-images.githubusercontent.com/80877629/231358916-5fce1e1c-1c2c-4549-bbc9-1ee21c6f2397.png">

**Comment by 1022ranji** [comment]
我暂时不建议把这个 developers 页面隐藏，原因有：
1. Docs 中的内容很多，这个页面作为摘要看起来比较一目了然。同时这个页面能够添加很多 EVM 的内容，和之前建的那个 issue 相关。
2. 这个页面有 Tech discussion 的链接，指向型讨论也比较清晰。

**Comment by wuminzhe** [comment]
the links that will be add here may not fall into these 4 types. we may only need 2 types: the api and the guide(or tutorial). and it may be different from what we are thinking. Our aim is to make out documentation useful. but now it content is no inefficitent.
* the api will has [sol sdk](https://docs.darwinia.network/solidity-sdk-85a817534fad4d8e80a0a79c10cd1d99) and [js sdk](https://docs.darwinia.network/darwinia-js-sdk-c4071940776544e7809005e0c249ebe9) .

**Comment by 1022ranji** [comment]
<img width="551" alt="image" src="https://user-images.githubusercontent.com/80877629/231421333-70d63f75-73ce-4fbd-b3e4-209e0d4fd3ce.png">
@isunaslabs 相关调整见文档：https://www.notion.so/itering/Developer-898a982e5c26470f801483e38920b80d
