### ISSUE TITLE
Update Docs' Links

### ISSUE THREAD

**Issue by 1022ranji** [darwinia-network/home#342]

**Comment by 1022ranji** [comment]
https://www.notion.so/itering/Home-5e5ab03206d64f49b1c228fdc9ca7edb?pvs=4

**Comment by hackfisher** [comment]
Partial done: https://github.com/darwinia-network/home/commit/7b051abf7a1bda4d98b5f25e2b0c0ddcaec69276

**Comment by isunaslabs** [comment]
I was planning to make a PR and do it now. I was finishing to read the last docs on WalletConnect

**Comment by isunaslabs** [comment]
I figured that it wouldn't take a long time that's why I was about to do it now

**Comment by 1022ranji** [comment]
done
