### ISSUE TITLE
Change the abstract and pdf.

### ISSUE THREAD

**Issue by 1022ranji** [darwinia-network/home#349]
https://darwinia.network/#/papers/1
<img width="1367" alt="image" src="https://github.com/darwinia-network/home/assets/80877629/2eb6fd08-d852-46d2-878a-bb035aa6be2f">

**Comment by 1022ranji** [comment]
The abstract will replace with this:
```
The blockchain industry has been evolving rapidly, witnessing the emergence of numerous blockchain networks. As proponents of a multi-chain future, we recognize the increasing need for interoperability among these diverse chains. While addressing this interoperability challenge, our focus extends beyond safety to encompass versatility, generalizability, and programmability.
Currently, several service providers offer token bridges for token holders. However, most of these solutions are limited to specific assets or use cases, lacking the desired level of generalization and programmability. Moreover, the complexity arising from layering application layer smart contracts on top of underlying cross-chain solutions further compromises security. To cater to the needs of cross-chain Dapp developers, there is a requirement for layered protocols, including a purpose-built, generalized, and programmable cross-chain messaging layer to support their applications.
```

**Comment by 1022ranji** [comment]
Pdf here:
[Genepaper_v3.pdf](https://github.com/darwinia-network/home/files/11765895/Genepaper_v3.pdf)

**Comment by wuminzhe** [comment]
Darwinia's goal is to provide developers and users with a versatile and programmable cross-chain platform that empowers the growth of the blockchain ecosystem. Darwinia Chain is an EVM-compatible smart contract platform operating as a parachain on Polkadot. It provides security and interoperability with Ethereum and other chains. Darwinia Chain utilizes the Ethereum Virtual Machine (EVM) to ensure compatibility with existing Ethereum infrastructure and programming languages. Darwinia Msgport enables communication between different chains, allowing for the development of multi-chain decentralized applications (Dapps). Msgport's architecture is modular and flexible, supporting various low-level cross-chain messaging protocols.
@1022ranji
