### ISSUE TITLE
Add use cases of xtoken by Helix

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/home#398]
cc @1022ranji @xiaoch05

**Comment by hackfisher** [comment]
https://docs.helixbridge.app/helixbridge/mapping_token

**Comment by nblogist** [comment]
hi @hackfisher where do you need these added? do you have specific direction?

**Comment by hackfisher** [comment]
> hi @hackfisher where do you need these added? do you have specific direction?

XToken is moving their website to xtoken.box and doing some refactor, let's wait for them and discuss in the next website and docs meeting?

**Comment by boundless-forest** [comment]
I think it has been added to the Msgport docs,  can be closed.
