### ISSUE TITLE
doc links changed 

### ISSUE THREAD

**Issue by wuminzhe** [darwinia-network/home#399]
most of the links on the Darwinia site are not working. (404 - not found)

**Comment by nblogist** [comment]
Happy to chime in and get it done once we have the link list!

**Comment by nblogist** [comment]
[Broken Links List](https://ahrefs.com/broken-link-checker/?input=https%3A%2F%2Fdarwinia.network%2F&mode=subdomains)

@JayJay1024 can you please share the updated links here! 15 links are broken

**Comment by JayJay1024** [comment]
> [Broken Links List](https://ahrefs.com/broken-link-checker/?input=https%3A%2F%2Fdarwinia.network%2F&mode=subdomains)
> 
> @JayJay1024 can you please share the updated links here! 15 links are broken

Maybe @wuminzhe can help provide the updated links?

**Comment by wuminzhe** [comment]
fixed
