### ISSUE TITLE
typo error

### ISSUE THREAD

**Issue by wuminzhe** [darwinia-network/home#420]
There's a lil typo error here
"Capabilities" :muscle::muscle:
@_akiwu
https://cdn.discordapp.com/attachments/1088285276507476029/1241358238256205895/image0.jpg?ex=6649e873&is=664896f3&hm=08cf45737090b113e1e60e138ed911dad6b8ffb589aa24f7334dc812a9ec40f0&

**Comment by hackfisher** [comment]
https://github.com/darwinia-network/home/commit/32675ede923f271526f3fc13ef520eedd962d546
